project_id = "kphdqgidwipqdthehckg"

[functions.text-to-speech]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false

[functions.jubee-conversation]
verify_jwt = false

[functions.send-screen-time-alert]
verify_jwt = false